# Generated by Django 3.2.3 on 2021-05-26 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(default='defaults/default-cover-pic.jpg', upload_to='images/cover_images/')),
                ('profile_pic', models.ImageField(default='defaults/default_profile_pic.jpg', upload_to='images/profile_pics')),
                ('location', models.CharField(blank=True, default='Planet Earth', max_length=50, null=True)),
                ('artistic_name', models.CharField(default='My photography portfolio', max_length=50)),
                ('bio', models.TextField(blank=True, default='My bio', null=True)),
                ('photographer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('featured', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=150)),
                ('camera_name', models.CharField(blank=True, default='unknown', max_length=100)),
                ('lens', models.CharField(blank=True, default='unknown', max_length=100)),
                ('used_light', models.CharField(choices=[('Natural light', 'Natural light'), ('Studio light', 'Studio light'), ('Mixed light', 'Mixed light')], default='Natural light', max_length=50)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioapp.portfolio')),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
