# Generated by Django 3.2.3 on 2021-06-01 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
    ]
