# Generated by Django 3.2.3 on 2021-06-01 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0004_alter_comment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='featured',
        ),
    ]
